service: enjoy-challenge-backend

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    TABLE: projects
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:DescribeTable
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TABLE}"
        
functions:
  getProject:
    handler: build/project/getProject.handler
    events:
    - http:
        path: /project/{projectId}
        method: get
  createProject:
    handler: build/project/createProject.handler
    events:
    - http:
        path: /project
        method: post
  setParticipation:
    handler: build/participation/setParticipation.handler
    events:
    - http:
        path: /project/{projectId}/set_participation
        method: put
  deleteParticipation:
    handler: build/participation/deleteParticipation.handler
    events:
    - http:
        path: /project/{projectId}/delete/{contributorId}
        method: put

resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.TABLE}